services:
  - type: web
    name: mednav-ai
    env: node
    buildCommand: npm install && npm run build
    startCommand: npx prisma db push --accept-data-loss && npm run start
    envVars:
      - key: DATABASE_URL
        value: file:./dev.db
      - key: NODE_ENV
        value: production
